services:
  - type: web
    name: ai-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn aibot.wsgi:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
