services:
  - type: web
    name: ai-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: OPENROUTER_API_KEY
        value: YOUR_OPENROUTER_API_KEY_HERE
